//
// Configuration.swift
//
// Generated by OpenAPI Generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

open class Configuration {

    /// The base URL for all API calls
    public static var host: String = "https://api.queueme.net"

    /// Configures the range of HTTP status codes that will result in a successful response
    ///
    /// If a HTTP status code is outside of this range the response will be interpreted as failed.
    public static var successfulStatusCodeRange: Range<Int> = 200..<300
}
