//
// BillingCycleEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;monthly&#x60; - monthly * &#x60;yearly&#x60; - yearly */
public enum BillingCycleEnum: String, Codable, CaseIterable {
    case monthly = "monthly"
    case yearly = "yearly"
}
