//
// ChurnPredictionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChurnPredictionRequest: Codable, JSONEncodable, Hashable {

    public var customerId: Int
    public var history: AnyCodable?

    public init(customerId: Int, history: AnyCodable?) {
        self.customerId = customerId
        self.history = history
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customerId = "customer_id"
        case history
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(customerId, forKey: .customerId)
        try container.encode(history, forKey: .history)
    }
}

