//
// CompanyDetailsModelStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;accepted&#x60; - Accepted * &#x60;rejected&#x60; - Rejected * &#x60;created&#x60; - Created */
public enum CompanyDetailsModelStatusEnum: String, Codable, CaseIterable {
    case accepted = "accepted"
    case rejected = "rejected"
    case created = "created"
}
