//
// CustomerSegmentationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerSegmentationRequest: Codable, JSONEncodable, Hashable {

    public var shopId: Int

    public init(shopId: Int) {
        self.shopId = shopId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shopId = "shop_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shopId, forKey: .shopId)
    }
}

