//
// CustomerSegmentationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CustomerSegmentationResponse: Codable, JSONEncodable, Hashable {

    public var segments: [[String: AnyCodable]]

    public init(segments: [[String: AnyCodable]]) {
        self.segments = segments
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case segments
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(segments, forKey: .segments)
    }
}

