//
// CustomersTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;male&#x60; - Male * &#x60;female&#x60; - Female * &#x60;both&#x60; - Both */
public enum CustomersTypeEnum: String, Codable, CaseIterable {
    case male = "male"
    case female = "female"
    case both = "both"
}
