//
// DayEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;monday&#x60; - Monday * &#x60;tuesday&#x60; - Tuesday * &#x60;wednesday&#x60; - Wednesday * &#x60;thursday&#x60; - Thursday * &#x60;friday&#x60; - Friday * &#x60;saturday&#x60; - Saturday * &#x60;sunday&#x60; - Sunday */
public enum DayEnum: String, Codable, CaseIterable {
    case monday = "monday"
    case tuesday = "tuesday"
    case wednesday = "wednesday"
    case thursday = "thursday"
    case friday = "friday"
    case saturday = "saturday"
    case sunday = "sunday"
}
