//
// DiscountTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;percentage&#x60; - Percentage * &#x60;amount&#x60; - Amount */
public enum DiscountTypeEnum: String, Codable, CaseIterable {
    case percentage = "percentage"
    case amount = "amount"
}
