//
// EmployeePerformanceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeePerformanceRequest: Codable, JSONEncodable, Hashable {

    public var employeeId: Int
    public var period: String

    public init(employeeId: Int, period: String) {
        self.employeeId = employeeId
        self.period = period
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case employeeId = "employee_id"
        case period
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(employeeId, forKey: .employeeId)
        try container.encode(period, forKey: .period)
    }
}

