//
// EmployeePerformanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeePerformanceResponse: Codable, JSONEncodable, Hashable {

    public var performanceScore: Double
    public var metrics: [String: Double]

    public init(performanceScore: Double, metrics: [String: Double]) {
        self.performanceScore = performanceScore
        self.metrics = metrics
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case performanceScore = "performance_score"
        case metrics
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(performanceScore, forKey: .performanceScore)
        try container.encode(metrics, forKey: .metrics)
    }
}

