//
// EmployeeRole.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeRole: Codable, JSONEncodable, Hashable {

    public static let roleRule = StringRule(minLength: nil, maxLength: 100, pattern: nil)
    public var id: Int
    public var role: String?
    /** Permissions for the role */
    public var permissions: AnyCodable?
    public var employee: Int?
    public var shop: Int

    public init(id: Int, role: String? = nil, permissions: AnyCodable? = nil, employee: Int? = nil, shop: Int) {
        self.id = id
        self.role = role
        self.permissions = permissions
        self.employee = employee
        self.shop = shop
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case role
        case permissions
        case employee
        case shop
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(role, forKey: .role)
        try container.encodeIfPresent(permissions, forKey: .permissions)
        try container.encodeIfPresent(employee, forKey: .employee)
        try container.encode(shop, forKey: .shop)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeRole: Identifiable {}
