//
// EmployeeWorkingHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmployeeWorkingHours: Codable, JSONEncodable, Hashable {

    public static let dayRule = StringRule(minLength: nil, maxLength: 20, pattern: nil)
    public var id: Int
    public var day: String
    public var startTime: String
    public var endTime: String

    public init(id: Int, day: String, startTime: String, endTime: String) {
        self.id = id
        self.day = day
        self.startTime = startTime
        self.endTime = endTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case day
        case startTime = "start_time"
        case endTime = "end_time"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(day, forKey: .day)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmployeeWorkingHours: Identifiable {}
