//
// FeedItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FeedItem: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var contentType: String
    public var createdAt: Date
    public var data: [String: AnyCodable]

    public init(id: Int, contentType: String, createdAt: Date, data: [String: AnyCodable]) {
        self.id = id
        self.contentType = contentType
        self.createdAt = createdAt
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case contentType = "content_type"
        case createdAt = "created_at"
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(data, forKey: .data)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension FeedItem: Identifiable {}
