//
// ForecastingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ForecastingRequest: Codable, JSONEncodable, Hashable {

    public var shopId: Int
    public var horizon: Int

    public init(shopId: Int, horizon: Int) {
        self.shopId = shopId
        self.horizon = horizon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case shopId = "shop_id"
        case horizon
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(horizon, forKey: .horizon)
    }
}

