//
// FraudDetectionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FraudDetectionResponse: Codable, JSONEncodable, Hashable {

    public var isFraud: Bool
    public var probability: Double

    public init(isFraud: Bool, probability: Double) {
        self.isFraud = isFraud
        self.probability = probability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isFraud = "is_fraud"
        case probability
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isFraud, forKey: .isFraud)
        try container.encode(probability, forKey: .probability)
    }
}

