//
// FraudDetectionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FraudDetectionRequest: Codable, JSONEncodable, Hashable {

    public var transactionId: String
    public var amount: Double

    public init(transactionId: String, amount: Double) {
        self.transactionId = transactionId
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transactionId = "transaction_id"
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transactionId, forKey: .transactionId)
        try container.encode(amount, forKey: .amount)
    }
}

