//
// ImageAnalysisResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageAnalysisResponse: Codable, JSONEncodable, Hashable {

    public var analysis: AnyCodable?

    public init(analysis: AnyCodable?) {
        self.analysis = analysis
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case analysis
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(analysis, forKey: .analysis)
    }
}

