//
// ImpressionTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;click&#x60; - Click * &#x60;view&#x60; - View */
public enum ImpressionTypeEnum: String, Codable, CaseIterable {
    case click = "click"
    case view = "view"
}
