//
// MerchantTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;freelance&#x60; - Freelance * &#x60;shop&#x60; - Shop */
public enum MerchantTypeEnum: String, Codable, CaseIterable {
    case freelance = "freelance"
    case shop = "shop"
}
