//
// Notifications.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Notifications: Codable, JSONEncodable, Hashable {

    public static let titleRule = StringRule(minLength: nil, maxLength: 255, pattern: nil)
    public var id: Int
    public var title: String
    public var message: String
    public var createdAt: Date
    public var isRead: Bool?
    public var user: Int

    public init(id: Int, title: String, message: String, createdAt: Date, isRead: Bool? = nil, user: Int) {
        self.id = id
        self.title = title
        self.message = message
        self.createdAt = createdAt
        self.isRead = isRead
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case message
        case createdAt = "created_at"
        case isRead = "is_read"
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(message, forKey: .message)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(isRead, forKey: .isRead)
        try container.encode(user, forKey: .user)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension Notifications: Identifiable {}
