//
// OnlinePaymentStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;pending&#x60; - Pending * &#x60;approved&#x60; - Approved * &#x60;rejected&#x60; - Rejected */
public enum OnlinePaymentStatusEnum: String, Codable, CaseIterable {
    case pending = "pending"
    case approved = "approved"
    case rejected = "rejected"
}
