//
// PatchedServiceExtendedDetailsModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedServiceExtendedDetailsModel: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var serviceName: String?
    public var overviews: [ServiceOverview]?
    public var faqs: [ServiceFAQ]?
    public var processSteps: [ServiceProcessStep]?
    public var benefits: [ServiceBenefit]?
    public var aftercareTips: [ServiceAftercareTip]?
    /** A detailed description of the service. */
    public var detailedDescription: String?
    public var updatedAt: Date?
    public var service: Int?

    public init(id: Int? = nil, serviceName: String? = nil, overviews: [ServiceOverview]? = nil, faqs: [ServiceFAQ]? = nil, processSteps: [ServiceProcessStep]? = nil, benefits: [ServiceBenefit]? = nil, aftercareTips: [ServiceAftercareTip]? = nil, detailedDescription: String? = nil, updatedAt: Date? = nil, service: Int? = nil) {
        self.id = id
        self.serviceName = serviceName
        self.overviews = overviews
        self.faqs = faqs
        self.processSteps = processSteps
        self.benefits = benefits
        self.aftercareTips = aftercareTips
        self.detailedDescription = detailedDescription
        self.updatedAt = updatedAt
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case serviceName = "service_name"
        case overviews
        case faqs
        case processSteps = "process_steps"
        case benefits
        case aftercareTips = "aftercare_tips"
        case detailedDescription = "detailed_description"
        case updatedAt = "updated_at"
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(serviceName, forKey: .serviceName)
        try container.encodeIfPresent(overviews, forKey: .overviews)
        try container.encodeIfPresent(faqs, forKey: .faqs)
        try container.encodeIfPresent(processSteps, forKey: .processSteps)
        try container.encodeIfPresent(benefits, forKey: .benefits)
        try container.encodeIfPresent(aftercareTips, forKey: .aftercareTips)
        try container.encodeIfPresent(detailedDescription, forKey: .detailedDescription)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(service, forKey: .service)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedServiceExtendedDetailsModel: Identifiable {}
