//
// PatchedShopAdsImpression.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedShopAdsImpression: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var impressionType: ImpressionTypeEnum?
    public var timestamp: Date?
    public var ad: Int?
    public var user: Int?

    public init(id: Int? = nil, impressionType: ImpressionTypeEnum? = nil, timestamp: Date? = nil, ad: Int? = nil, user: Int? = nil) {
        self.id = id
        self.impressionType = impressionType
        self.timestamp = timestamp
        self.ad = ad
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case impressionType = "impression_type"
        case timestamp
        case ad
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(impressionType, forKey: .impressionType)
        try container.encodeIfPresent(timestamp, forKey: .timestamp)
        try container.encodeIfPresent(ad, forKey: .ad)
        try container.encodeIfPresent(user, forKey: .user)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedShopAdsImpression: Identifiable {}
