//
// PatchedChatHistory.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedChatHistory: Codable, JSONEncodable, Hashable {

    public static let sentByRule = NumericRule<Int64>(minimum: -9223372036854775808, exclusiveMinimum: false, maximum: 9223372036854775807, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int?
    public var botResponse: String?
    public var sentBy: Int64?
    public var message: String?
    public var createdAt: Date?
    public var room: Int?

    public init(id: Int? = nil, botResponse: String? = nil, sentBy: Int64? = nil, message: String? = nil, createdAt: Date? = nil, room: Int? = nil) {
        self.id = id
        self.botResponse = botResponse
        self.sentBy = sentBy
        self.message = message
        self.createdAt = createdAt
        self.room = room
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case botResponse = "bot_response"
        case sentBy = "sent_by"
        case message
        case createdAt
        case room
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(botResponse, forKey: .botResponse)
        try container.encodeIfPresent(sentBy, forKey: .sentBy)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(room, forKey: .room)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedChatHistory: Identifiable {}
