//
// PatchedShopGalleryImagesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedShopGalleryImagesModel: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var image: String?
    public var shop: Int?

    public init(id: Int? = nil, image: String? = nil, shop: Int? = nil) {
        self.id = id
        self.image = image
        self.shop = shop
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case image
        case shop
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(shop, forKey: .shop)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedShopGalleryImagesModel: Identifiable {}
