//
// PatchedShopFollow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedShopFollow: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var shop: ShopDetailsModel?
    public var shopId: Int?
    public var createdAt: Date?

    public init(id: Int? = nil, shop: ShopDetailsModel? = nil, shopId: Int? = nil, createdAt: Date? = nil) {
        self.id = id
        self.shop = shop
        self.shopId = shopId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case shop
        case shopId = "shop_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(shop, forKey: .shop)
        try container.encodeIfPresent(shopId, forKey: .shopId)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedShopFollow: Identifiable {}
