//
// PatchedComment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedComment: Codable, JSONEncodable, Hashable {

    public var id: Int?
    /** Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
    public var user: String?
    public var reel: Int?
    public var text: String?
    public var createdAt: Date?
    public var likeCount: Int?
    public var parent: Int?
    public var replies: [String: AnyCodable]?

    public init(id: Int? = nil, user: String? = nil, reel: Int? = nil, text: String? = nil, createdAt: Date? = nil, likeCount: Int? = nil, parent: Int? = nil, replies: [String: AnyCodable]? = nil) {
        self.id = id
        self.user = user
        self.reel = reel
        self.text = text
        self.createdAt = createdAt
        self.likeCount = likeCount
        self.parent = parent
        self.replies = replies
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case user
        case reel
        case text
        case createdAt = "created_at"
        case likeCount = "like_count"
        case parent
        case replies
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(user, forKey: .user)
        try container.encodeIfPresent(reel, forKey: .reel)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(likeCount, forKey: .likeCount)
        try container.encodeIfPresent(parent, forKey: .parent)
        try container.encodeIfPresent(replies, forKey: .replies)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedComment: Identifiable {}
