//
// PatchedShopServiceCategoryModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedShopServiceCategoryModel: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public var id: Int?
    public var name: String?
    public var createdAt: Date?
    public var forecastData: AnyCodable?

    public init(id: Int? = nil, name: String? = nil, createdAt: Date? = nil, forecastData: AnyCodable? = nil) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.forecastData = forecastData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt = "created_at"
        case forecastData = "forecast_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(forecastData, forKey: .forecastData)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedShopServiceCategoryModel: Identifiable {}
