//
// PatchedShopServiceGalleryModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PatchedShopServiceGalleryModel: Codable, JSONEncodable, Hashable {

    public var id: Int?
    public var file: String?
    public var service: Int?

    public init(id: Int? = nil, file: String? = nil, service: Int? = nil) {
        self.id = id
        self.file = file
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case file
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(file, forKey: .file)
        try container.encodeIfPresent(service, forKey: .service)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension PatchedShopServiceGalleryModel: Identifiable {}
