//
// PaymentProcessingRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentProcessingRequest: Codable, JSONEncodable, Hashable {

    public var paymentId: String
    public var paymentFor: PaymentForEnum

    public init(paymentId: String, paymentFor: PaymentForEnum) {
        self.paymentId = paymentId
        self.paymentFor = paymentFor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentId = "payment_id"
        case paymentFor = "payment_for"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paymentId, forKey: .paymentId)
        try container.encode(paymentFor, forKey: .paymentFor)
    }
}

