//
// PaymentProcessingResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentProcessingResponse: Codable, JSONEncodable, Hashable {

    public var paymentStatus: String

    public init(paymentStatus: String) {
        self.paymentStatus = paymentStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentStatus = "payment_status"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paymentStatus, forKey: .paymentStatus)
    }
}

