//
// PaymentCreateRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentCreateRequest: Codable, JSONEncodable, Hashable {

    public static let amountRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^-?\\d{0,8}(?:\\.\\d{0,2})?$/")
    public var paymentFor: PaymentForEnum
    public var amount: Decimal
    public var source: [String: String]?
    public var metadata: [String: String]?
    public var description: String?

    public init(paymentFor: PaymentForEnum, amount: Decimal, source: [String: String]? = nil, metadata: [String: String]? = nil, description: String? = nil) {
        self.paymentFor = paymentFor
        self.amount = amount
        self.source = source
        self.metadata = metadata
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentFor = "payment_for"
        case amount
        case source
        case metadata
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paymentFor, forKey: .paymentFor)
        try container.encode(amount, forKey: .amount)
        try container.encodeIfPresent(source, forKey: .source)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

