//
// PaymentCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PaymentCreateResponse: Codable, JSONEncodable, Hashable {

    public var payment: [String: AnyCodable]
    public var paymentRecordId: Int

    public init(payment: [String: AnyCodable], paymentRecordId: Int) {
        self.payment = payment
        self.paymentRecordId = paymentRecordId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case payment
        case paymentRecordId = "payment_record_id"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(payment, forKey: .payment)
        try container.encode(paymentRecordId, forKey: .paymentRecordId)
    }
}

