//
// PersonalizationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PersonalizationResponse: Codable, JSONEncodable, Hashable {

    public var recommendations: [[String: AnyCodable]]

    public init(recommendations: [[String: AnyCodable]]) {
        self.recommendations = recommendations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recommendations
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recommendations, forKey: .recommendations)
    }
}

