//
// RegistrationOTPResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegistrationOTPResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var otp: String?

    public init(message: String, otp: String? = nil) {
        self.message = message
        self.otp = otp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case otp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encodeIfPresent(otp, forKey: .otp)
    }
}

