//
// RegisterUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterUserRequest: Codable, JSONEncodable, Hashable {

    public var phoneNumber: String
    public var password: String
    public var otp: String

    public init(phoneNumber: String, password: String, otp: String) {
        self.phoneNumber = phoneNumber
        self.password = password
        self.otp = otp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case phoneNumber = "phone_number"
        case password
        case otp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(phoneNumber, forKey: .phoneNumber)
        try container.encode(password, forKey: .password)
        try container.encode(otp, forKey: .otp)
    }
}

