//
// RegisterCompanyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterCompanyResponse: Codable, JSONEncodable, Hashable {

    public var company: CompanyDetailsModel

    public init(company: CompanyDetailsModel) {
        self.company = company
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case company
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(company, forKey: .company)
    }
}

