//
// RegisterCompanyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterCompanyRequest: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 300, pattern: nil)
    public var userId: Int
    public var name: String
    public var description: String?
    public var address: String?
    public var merchantType: MerchantTypeEnum

    public init(userId: Int, name: String, description: String? = nil, address: String? = nil, merchantType: MerchantTypeEnum) {
        self.userId = userId
        self.name = name
        self.description = description
        self.address = address
        self.merchantType = merchantType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case userId = "user_id"
        case name
        case description
        case address
        case merchantType = "merchant_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(userId, forKey: .userId)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(address, forKey: .address)
        try container.encode(merchantType, forKey: .merchantType)
    }
}

