//
// RegisterUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct RegisterUserResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var userId: Int
    public var access: String
    public var refresh: String

    public init(message: String, userId: Int, access: String, refresh: String) {
        self.message = message
        self.userId = userId
        self.access = access
        self.refresh = refresh
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case userId = "user_id"
        case access
        case refresh
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(userId, forKey: .userId)
        try container.encode(access, forKey: .access)
        try container.encode(refresh, forKey: .refresh)
    }
}

