//
// SentimentEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;positive&#x60; - Positive * &#x60;neutral&#x60; - Neutral * &#x60;negative&#x60; - Negative */
public enum SentimentEnum: String, Codable, CaseIterable {
    case positive = "positive"
    case neutral = "neutral"
    case negative = "negative"
}
