//
// SentimentResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SentimentResponse: Codable, JSONEncodable, Hashable {

    public var sentiment: SentimentEnum
    public var score: Double

    public init(sentiment: SentimentEnum, score: Double) {
        self.sentiment = sentiment
        self.score = score
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sentiment
        case score
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sentiment, forKey: .sentiment)
        try container.encode(score, forKey: .score)
    }
}

