//
// ServiceLocationEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;in_store&#x60; - In Store * &#x60;at_shop&#x60; - At Shop * &#x60;both&#x60; - Both */
public enum ServiceLocationEnum: String, Codable, CaseIterable {
    case inStore = "in_store"
    case atShop = "at_shop"
    case both = "both"
}
