//
// ServiceProcessStep.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceProcessStep: Codable, JSONEncodable, Hashable {

    public static let orderIndexRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: 9223372036854775807, exclusiveMaximum: false, multipleOf: nil)
    public static let titleRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public var id: Int
    /** Order index for display */
    public var orderIndex: Int64?
    /** Title of the process step */
    public var title: String
    /** Optional image for the step */
    public var image: String?
    /** Description of this process step */
    public var description: String?
    public var extendedDetails: Int

    public init(id: Int, orderIndex: Int64? = nil, title: String, image: String? = nil, description: String? = nil, extendedDetails: Int) {
        self.id = id
        self.orderIndex = orderIndex
        self.title = title
        self.image = image
        self.description = description
        self.extendedDetails = extendedDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case orderIndex = "order_index"
        case title
        case image
        case description
        case extendedDetails = "extended_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(orderIndex, forKey: .orderIndex)
        try container.encode(title, forKey: .title)
        try container.encodeIfPresent(image, forKey: .image)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(extendedDetails, forKey: .extendedDetails)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceProcessStep: Identifiable {}
