//
// ServiceTypeEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;in_shop&#x60; - In Shop * &#x60;at_home&#x60; - At Home * &#x60;both&#x60; - Both */
public enum ServiceTypeEnum: String, Codable, CaseIterable {
    case inShop = "in_shop"
    case atHome = "at_home"
    case both = "both"
}
