//
// ServiceAftercareTip.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ServiceAftercareTip: Codable, JSONEncodable, Hashable {

    public static let tipTextRule = StringRule(minLength: nil, maxLength: 300, pattern: nil)
    public static let orderIndexRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: 9223372036854775807, exclusiveMaximum: false, multipleOf: nil)
    public var id: Int
    public var tipText: String
    public var orderIndex: Int64?
    public var extendedDetails: Int

    public init(id: Int, tipText: String, orderIndex: Int64? = nil, extendedDetails: Int) {
        self.id = id
        self.tipText = tipText
        self.orderIndex = orderIndex
        self.extendedDetails = extendedDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case tipText = "tip_text"
        case orderIndex = "order_index"
        case extendedDetails = "extended_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(tipText, forKey: .tipText)
        try container.encodeIfPresent(orderIndex, forKey: .orderIndex)
        try container.encode(extendedDetails, forKey: .extendedDetails)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ServiceAftercareTip: Identifiable {}
