//
// ServiceBookingDetailsModelStatusEnum.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** * &#x60;requested&#x60; - Requested * &#x60;booked&#x60; - Booked * &#x60;completed&#x60; - Completed * &#x60;cancelled&#x60; - Cancelled */
public enum ServiceBookingDetailsModelStatusEnum: String, Codable, CaseIterable {
    case requested = "requested"
    case booked = "booked"
    case completed = "completed"
    case cancelled = "cancelled"
}
