//
// ShopServiceGalleryModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopServiceGalleryModel: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var file: String
    public var service: Int

    public init(id: Int, file: String, service: Int) {
        self.id = id
        self.file = file
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case file
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(file, forKey: .file)
        try container.encode(service, forKey: .service)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopServiceGalleryModel: Identifiable {}
