//
// ShopGalleryImagesModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopGalleryImagesModel: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var image: String
    public var shop: Int

    public init(id: Int, image: String, shop: Int) {
        self.id = id
        self.image = image
        self.shop = shop
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case image
        case shop
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(image, forKey: .image)
        try container.encode(shop, forKey: .shop)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopGalleryImagesModel: Identifiable {}
