//
// ShopServiceTimeSlot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopServiceTimeSlot: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var day: DayEnum
    public var startTime: String
    public var endTime: String
    public var createdAt: Date

    public init(id: Int, day: DayEnum, startTime: String, endTime: String, createdAt: Date) {
        self.id = id
        self.day = day
        self.startTime = startTime
        self.endTime = endTime
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case day
        case startTime = "start_time"
        case endTime = "end_time"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(day, forKey: .day)
        try container.encode(startTime, forKey: .startTime)
        try container.encode(endTime, forKey: .endTime)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopServiceTimeSlot: Identifiable {}
