//
// ShopAdsImpression.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopAdsImpression: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var impressionType: ImpressionTypeEnum?
    public var timestamp: Date
    public var ad: Int
    public var user: Int

    public init(id: Int, impressionType: ImpressionTypeEnum? = nil, timestamp: Date, ad: Int, user: Int) {
        self.id = id
        self.impressionType = impressionType
        self.timestamp = timestamp
        self.ad = ad
        self.user = user
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case impressionType = "impression_type"
        case timestamp
        case ad
        case user
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(impressionType, forKey: .impressionType)
        try container.encode(timestamp, forKey: .timestamp)
        try container.encode(ad, forKey: .ad)
        try container.encode(user, forKey: .user)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopAdsImpression: Identifiable {}
