//
// ShopServiceCategoryModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopServiceCategoryModel: Codable, JSONEncodable, Hashable {

    public static let nameRule = StringRule(minLength: nil, maxLength: 200, pattern: nil)
    public var id: Int
    public var name: String
    public var createdAt: Date
    public var forecastData: AnyCodable?

    public init(id: Int, name: String, createdAt: Date, forecastData: AnyCodable?) {
        self.id = id
        self.name = name
        self.createdAt = createdAt
        self.forecastData = forecastData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case createdAt = "created_at"
        case forecastData = "forecast_data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(forecastData, forKey: .forecastData)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopServiceCategoryModel: Identifiable {}
