//
// ShopFollow.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ShopFollow: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var shop: ShopDetailsModel
    public var shopId: Int
    public var createdAt: Date

    public init(id: Int, shop: ShopDetailsModel, shopId: Int, createdAt: Date) {
        self.id = id
        self.shop = shop
        self.shopId = shopId
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case shop
        case shopId = "shop_id"
        case createdAt = "created_at"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(shop, forKey: .shop)
        try container.encode(shopId, forKey: .shopId)
        try container.encode(createdAt, forKey: .createdAt)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension ShopFollow: Identifiable {}
