//
// SubscriptionPaymentIntegrationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Response after integrating a subscription payment. */
public struct SubscriptionPaymentIntegrationResponse: Codable, JSONEncodable, Hashable {

    public var message: String
    public var plan: Int
    public var paymentId: String
    public var status: String

    public init(message: String, plan: Int, paymentId: String, status: String) {
        self.message = message
        self.plan = plan
        self.paymentId = paymentId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case plan
        case paymentId = "payment_id"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(plan, forKey: .plan)
        try container.encode(paymentId, forKey: .paymentId)
        try container.encode(status, forKey: .status)
    }
}

