//
// SubscriptionPaymentIntegrationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Request payload for associating a payment with a subscription. */
public struct SubscriptionPaymentIntegrationRequest: Codable, JSONEncodable, Hashable {

    public var company: Int
    public var plan: Int
    public var billingCycle: BillingCycleEnum
    public var paymentId: String
    public var status: String

    public init(company: Int, plan: Int, billingCycle: BillingCycleEnum, paymentId: String, status: String) {
        self.company = company
        self.plan = plan
        self.billingCycle = billingCycle
        self.paymentId = paymentId
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case company
        case plan
        case billingCycle = "billing_cycle"
        case paymentId = "payment_id"
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(company, forKey: .company)
        try container.encode(plan, forKey: .plan)
        try container.encode(billingCycle, forKey: .billingCycle)
        try container.encode(paymentId, forKey: .paymentId)
        try container.encode(status, forKey: .status)
    }
}

