//
// TokenObtainPair.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TokenObtainPair: Codable, JSONEncodable, Hashable {

    public var username: String
    public var password: String
    public var access: String
    public var refresh: String

    public init(username: String, password: String, access: String, refresh: String) {
        self.username = username
        self.password = password
        self.access = access
        self.refresh = refresh
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case password
        case access
        case refresh
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(password, forKey: .password)
        try container.encode(access, forKey: .access)
        try container.encode(refresh, forKey: .refresh)
    }
}

