//
// UsersAppRegisterUserResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersAppRegisterUserResponse: Codable, JSONEncodable, Hashable {

    public var id: Int
    public var username: String
    public var name: String
    public var phoneNumber: String

    public init(id: Int, username: String, name: String, phoneNumber: String) {
        self.id = id
        self.username = username
        self.name = name
        self.phoneNumber = phoneNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case username
        case name
        case phoneNumber = "phone_number"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(username, forKey: .username)
        try container.encode(name, forKey: .name)
        try container.encode(phoneNumber, forKey: .phoneNumber)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension UsersAppRegisterUserResponse: Identifiable {}
