//
// UserMasterDetailsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserMasterDetailsResponse: Codable, JSONEncodable, Hashable {

    public var user: User
    public var customerDetails: [String: AnyCodable]?
    public var companyDetails: [String: AnyCodable]?
    public var employeeDetails: [String: AnyCodable]?
    public var subscriptionDetails: [String: AnyCodable]?

    public init(user: User, customerDetails: [String: AnyCodable]?, companyDetails: [String: AnyCodable]?, employeeDetails: [String: AnyCodable]?, subscriptionDetails: [String: AnyCodable]?) {
        self.user = user
        self.customerDetails = customerDetails
        self.companyDetails = companyDetails
        self.employeeDetails = employeeDetails
        self.subscriptionDetails = subscriptionDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case customerDetails = "customer_details"
        case companyDetails = "company_details"
        case employeeDetails = "employee_details"
        case subscriptionDetails = "subscription_details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encode(customerDetails, forKey: .customerDetails)
        try container.encode(companyDetails, forKey: .companyDetails)
        try container.encode(employeeDetails, forKey: .employeeDetails)
        try container.encode(subscriptionDetails, forKey: .subscriptionDetails)
    }
}

