//
// UsersAppRegisterUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UsersAppRegisterUserRequest: Codable, JSONEncodable, Hashable {

    public var name: String
    public var phoneNumber: String
    public var otp: String

    public init(name: String, phoneNumber: String, otp: String) {
        self.name = name
        self.phoneNumber = phoneNumber
        self.otp = otp
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case phoneNumber = "phone_number"
        case otp
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(phoneNumber, forKey: .phoneNumber)
        try container.encode(otp, forKey: .otp)
    }
}

