//
// WebhookData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct WebhookData: Codable, JSONEncodable, Hashable {

    public var id: String
    public var status: String
    public var amount: String
    public var metadata: WebhookMetadata

    public init(id: String, status: String, amount: String, metadata: WebhookMetadata) {
        self.id = id
        self.status = status
        self.amount = amount
        self.metadata = metadata
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case status
        case amount
        case metadata
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(amount, forKey: .amount)
        try container.encode(metadata, forKey: .metadata)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension WebhookData: Identifiable {}
