//
// CompanyAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class CompanyAPI {

    /**

     - parameter registerCompanyRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func companyRegisterCreate(registerCompanyRequest: RegisterCompanyRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: RegisterCompanyResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return companyRegisterCreateWithRequestBuilder(registerCompanyRequest: registerCompanyRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /company/register/
     - POST /company/register/
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter registerCompanyRequest: (body)  
     - returns: RequestBuilder<RegisterCompanyResponse> 
     */
    open class func companyRegisterCreateWithRequestBuilder(registerCompanyRequest: RegisterCompanyRequest) -> RequestBuilder<RegisterCompanyResponse> {
        let localVariablePath = "/company/register/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: registerCompanyRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RegisterCompanyResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
