//
// UsersAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class UsersAPI {

    /**

     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func usersMasterDetailsRetrieve(apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: UserMasterDetailsResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return usersMasterDetailsRetrieveWithRequestBuilder().execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - GET /users/master-details/
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - returns: RequestBuilder<UserMasterDetailsResponse> 
     */
    open class func usersMasterDetailsRetrieveWithRequestBuilder() -> RequestBuilder<UserMasterDetailsResponse> {
        let localVariablePath = "/users/master-details/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters: [String: Any]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UserMasterDetailsResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter usersAppRegisterUserRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func usersRegisterCreate(usersAppRegisterUserRequest: UsersAppRegisterUserRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: UsersAppRegisterUserResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return usersRegisterCreateWithRequestBuilder(usersAppRegisterUserRequest: usersAppRegisterUserRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /users/register/
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter usersAppRegisterUserRequest: (body)  
     - returns: RequestBuilder<UsersAppRegisterUserResponse> 
     */
    open class func usersRegisterCreateWithRequestBuilder(usersAppRegisterUserRequest: UsersAppRegisterUserRequest) -> RequestBuilder<UsersAppRegisterUserResponse> {
        let localVariablePath = "/users/register/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: usersAppRegisterUserRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UsersAppRegisterUserResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }

    /**

     - parameter updateProfileSuggestRequest: (body)  
     - parameter apiResponseQueue: The queue on which api response is dispatched.
     - parameter completion: completion handler to receive the data and the error objects
     */
    @discardableResult
    open class func usersUpdateProfileSuggestCreate(updateProfileSuggestRequest: UpdateProfileSuggestRequest, apiResponseQueue: DispatchQueue = OpenAPIClientAPI.apiResponseQueue, completion: @escaping ((_ data: UpdateProfileSuggestResponse?, _ error: Error?) -> Void)) -> RequestTask {
        return usersUpdateProfileSuggestCreateWithRequestBuilder(updateProfileSuggestRequest: updateProfileSuggestRequest).execute(apiResponseQueue) { result in
            switch result {
            case let .success(response):
                completion(response.body, nil)
            case let .failure(error):
                completion(nil, error)
            }
        }
    }

    /**
     - POST /users/update-profile-suggest/
     - Bearer Token:
       - type: http
       - name: jwtAuth
     - parameter updateProfileSuggestRequest: (body)  
     - returns: RequestBuilder<UpdateProfileSuggestResponse> 
     */
    open class func usersUpdateProfileSuggestCreateWithRequestBuilder(updateProfileSuggestRequest: UpdateProfileSuggestRequest) -> RequestBuilder<UpdateProfileSuggestResponse> {
        let localVariablePath = "/users/update-profile-suggest/"
        let localVariableURLString = OpenAPIClientAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateProfileSuggestRequest)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UpdateProfileSuggestResponse>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
